services:
  requests:
    build: ./src/requests-service/Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:adminpassword@requests_db:5432/requests_service
    ports:
      - '8001:8001'
    depends_on:
      - requests_db
    networks: [backend]

  brigades:
    build: ./src/brigades-service/Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:adminpassword@brigades_db:5432/brigades_service
    ports:
      - '8002:8002'
    depends_on:
      - brigades_db
    networks: [backend]

  users:
    build: ./src/users-service/Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:adminpassword@users_db:5432/users_service
    ports:
      - '8003:8003'
    depends_on:
      - users_db
    networks: [backend]

  workplans:
    build: ./src/workplans-service/Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:adminpassword@workplans_db:5432/workplans_service
      USERS_SERVICE_URL: http://users:8003
    ports:
      - '8004:8004'
    depends_on:
      - workplans_db
      - users
    networks: [backend]

  workplans_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: workplans_service
    networks: [backend]

  brigades_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: brigades_service
    networks: [backend]

  users_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: users_service
    networks: [backend]

  requests_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: requests_service
    networks: [backend]

networks:
  backend:
    driver: bridge
